import MainHeader from '@/Components/MainHeader';
import './globals.css';
import { Manrope } from 'next/font/google';
import Footer from '@/Components/Footer';

const manrope = Manrope({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={manrope.className}>
        <MainHeader />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
